-- sudo su postgres
-- createuser clothes_user
-- createdb clothes_db --owner clothes_user
-- psql
-- alter user clothes_user with password '12345';
-- \q
-- psql clothes_db


DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"price" integer,
"stock" integer,
"gender" integer
);


REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO clothes_user;

REVOKE ALL ON products FROM public;
GRANT ALL ON products TO clothes_user;

INSERT INTO products (name, price, stock, gender) VALUES ('pantalones', 2000, 6, 1);
INSERT INTO products (name, price, stock, gender) VALUES ('camiseta', 2200, 4, 1);
INSERT INTO products (name, price, stock, gender) VALUES ('chaqueta', 1000, 1, 1);
INSERT INTO products (name, price, stock, gender) VALUES ('camisa', 3300, 7, 1);
INSERT INTO products (name, price, stock, gender) VALUES ('calcetines', 500, 0, 1);
INSERT INTO products (name, price, stock, gender) VALUES ('blusa', 1800, 1, 2);
INSERT INTO products (name, price, stock, gender) VALUES ('vestido', 4500, 4, 2);
INSERT INTO products (name, price, stock, gender) VALUES ('falda', 3000, 2, 2);
INSERT INTO products (name, price, stock, gender) VALUES ('medias', 1000, 0, 2);
INSERT INTO products (name, price, stock, gender) VALUES ('zapatos de tacón', 3400, 3, 2);

-- \q
-- exit